apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations: {}
  generateName: helm-chart-oci-publish-run-
  namespace: cicd
spec:
  params:
    - name: namespace
      value: cicd
    - name: repository
      value: nguiland-ops-helm
    - name: charts-dir
      value: addons
    - name: excluded-charts
      value: cronjob-common
    - name: registry
      value: oci://artifactory-jcr.${ENVIRONMENT}/docker-local
    - name: artifactory-readiness-timeout
      value: 15m
    - name: skip-tls
      value: "false"
  pipelineRef:
    name: helm-chart-oci-publish
  taskRunTemplate:
    podTemplate:
      securityContext:
        fsGroup: 65532
    serviceAccountName: tekton-pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: helm-source
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
          labels:
            tekton.dev/pvc-protection-finalizer: remove
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi
        status: {}
    - name: manifest-dir
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
          labels:
            tekton.dev/pvc-protection-finalizer: remove
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Mi
        status: {}
    - name: docker-config
      secret:
        secretName: docker-config
    - name: ssh-directory
      secret:
        secretName: ssh-credentials
